project 'Starter.xcodeproj/'

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'
use_frameworks!

abstract_target "StarterTargets" do
  pod 'StarterCore', :path => '../'
  pod 'RxSwift', '~> 4.4.0'
  pod 'RxCocoa', '~> 4.4.0'
  pod 'KeychainAccess', '~> 3.1.2'
  pod 'JWTDecode', '~> 2.2'
  pod 'MaterialComponents', '~> 75.0.1'
  pod 'Swinject', '~> 2.5.0'
  pod 'SwinjectAutoregistration', '~> 2.5.0'
  pod 'MoreCodable', '~> 0.2.0'

  target 'Starter'
end
